#!/usr/bin/env python3
"""
generate_stl.py -- batch STL generation from chassis.scad

Purpose
-------
WRO Future Engineers team helper: run this script to produce STL files from
the parametric OpenSCAD model -- one per part, ready for 3D-printing or
import into Cura / PrusaSlicer / Bambu Studio.

Dependencies
------------
- Python 3.8+
- OpenSCAD (https://openscad.org/downloads.html) -- installed separately.
  This script auto-locates the binary in the standard macOS / Linux / Windows paths.

Usage
-----
    python3 generate_stl.py                # generate every part (default)
    python3 generate_stl.py --list         # list available parts
    python3 generate_stl.py --part 01_chassis_plate
    python3 generate_stl.py --outdir ./stl_v2 --quality high
"""

from __future__ import annotations
import argparse
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SCAD_FILE = ROOT / "chassis.scad"
DEFAULT_OUTDIR = ROOT / "stl"

# ----------------------------------------------------------------------------
# Parts list: file name -> OpenSCAD module call.
# Extend as needed by adding any module defined in chassis.scad.
# ----------------------------------------------------------------------------
PARTS: dict[str, dict] = {
    "00_full_assembly": {
        "call": "assemble();",
        "desc": "Full chassis assembly (for visualization / reference)",
    },
    "01_chassis_plate": {
        "call": "chassis_plate();",
        "desc": "Main plate (print in ABS / PETG, 3-4 mm)",
    },
    "02_upper_deck": {
        "call": "upper_deck();",
        "desc": "Upper T-shaped deck",
    },
    "03_shock_tower_front": {
        "call": "shock_tower(0);",
        "desc": "Shock tower (front and rear are identical)",
    },
    "04_lower_arm_left": {
        "call": "suspension_arm(length=55, w=12, side=-1);",
        "desc": "Left lower suspension arm",
    },
    "04_lower_arm_right": {
        "call": "suspension_arm(length=55, w=12, side=1);",
        "desc": "Right lower suspension arm",
    },
    "05_upper_arm_left": {
        "call": "suspension_arm(length=43, w=5, side=-1);",
        "desc": "Left upper suspension arm",
    },
    "05_upper_arm_right": {
        "call": "suspension_arm(length=43, w=5, side=1);",
        "desc": "Right upper suspension arm",
    },
    "06_steering_hub_left": {
        "call": "steering_hub(side=-1);",
        "desc": "Left steering hub (front)",
    },
    "06_steering_hub_right": {
        "call": "steering_hub(side=1);",
        "desc": "Right steering hub (front)",
    },
    "07_body_post": {
        "call": "body_post(56);",
        "desc": "Body post (4 needed)",
    },
    "08_foam_bumper": {
        "call": "foam_bumper();",
        "desc": "Foam bumper (2 needed -- front/rear)",
    },
    "09_antenna_mount": {
        "call": "antenna_mount();",
        "desc": "Antenna mount",
    },
    "10_wheel": {
        "call": "wheel();",
        "desc": "Full wheel (reference only -- impractical to print)",
    },
    "11_battery_dummy": {
        "call": "battery();",
        "desc": "Battery shape mockup",
    },
    "12_motor_dummy": {
        "call": "motor();",
        "desc": "Motor shape mockup",
    },
}

# Render quality -> $fn value in OpenSCAD
QUALITY_PRESETS = {
    "draft":  32,
    "normal": 64,
    "high":   128,
    "ultra":  256,
}


def find_openscad() -> str | None:
    """Locate the OpenSCAD binary in standard system paths."""
    candidates = [
        "openscad",
        "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD",
        "/usr/bin/openscad",
        "/usr/local/bin/openscad",
        "/opt/homebrew/bin/openscad",
        "C:/Program Files/OpenSCAD/openscad.exe",
        "C:/Program Files (x86)/OpenSCAD/openscad.exe",
    ]
    for c in candidates:
        if shutil.which(c):
            return shutil.which(c)
        p = Path(c)
        if p.exists():
            return str(p)
    return None


def render_part(scad_call: str, output_stl: Path, openscad_bin: str, fn_quality: int) -> tuple[bool, str]:
    """Render one part: temp .scad -> STL via OpenSCAD."""
    wrapper = f"""// auto-generated by generate_stl.py
$fn = {fn_quality};
use <{SCAD_FILE.as_posix()}>;
{scad_call}
"""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".scad", delete=False, encoding="utf-8") as tmp:
        tmp.write(wrapper)
        tmp_path = Path(tmp.name)
    try:
        proc = subprocess.run(
            [openscad_bin, "-o", str(output_stl), str(tmp_path)],
            capture_output=True, text=True, timeout=180,
        )
        if proc.returncode != 0:
            return False, proc.stderr.strip() or proc.stdout.strip() or "unknown error"
        return True, ""
    except subprocess.TimeoutExpired:
        return False, "timeout (>180s)"
    finally:
        tmp_path.unlink(missing_ok=True)


def fmt_size(n_bytes: int) -> str:
    if n_bytes < 1024:
        return f"{n_bytes} B"
    if n_bytes < 1024 * 1024:
        return f"{n_bytes / 1024:.1f} KB"
    return f"{n_bytes / 1024 / 1024:.2f} MB"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate STL files from the parametric chassis.scad model",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--list", action="store_true", help="List available parts and exit")
    parser.add_argument("--part", action="append", default=None,
                        help="Part name (repeatable). Default: all parts.")
    parser.add_argument("--outdir", default=str(DEFAULT_OUTDIR),
                        help=f"STL output directory (default: {DEFAULT_OUTDIR})")
    parser.add_argument("--quality", choices=list(QUALITY_PRESETS), default="normal",
                        help="Render quality ($fn): draft=32, normal=64, high=128, ultra=256")
    parser.add_argument("--openscad", default=None,
                        help="Path to OpenSCAD (override auto-detect)")
    args = parser.parse_args()

    if args.list:
        print("\nAvailable parts:\n" + "-" * 60)
        for name, info in PARTS.items():
            print(f"  {name:<28} -- {info['desc']}")
        print()
        return 0

    if not SCAD_FILE.exists():
        print(f"ERROR: {SCAD_FILE} not found", file=sys.stderr)
        return 2

    openscad = args.openscad or find_openscad()
    if not openscad:
        print("ERROR: OpenSCAD not found.", file=sys.stderr)
        print("Free download: https://openscad.org/downloads.html", file=sys.stderr)
        print("Or pass an explicit path: --openscad /path/to/openscad", file=sys.stderr)
        return 3

    print(f"OpenSCAD: {openscad}")
    print(f"SCAD file: {SCAD_FILE}")
    print(f"Quality ($fn): {QUALITY_PRESETS[args.quality]}")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    print(f"Output dir: {outdir.resolve()}\n")

    targets = args.part if args.part else list(PARTS.keys())
    bad = [t for t in targets if t not in PARTS]
    if bad:
        print(f"ERROR: unknown parts: {bad}", file=sys.stderr)
        print("Run --list to see available names.", file=sys.stderr)
        return 4

    fn = QUALITY_PRESETS[args.quality]
    ok, fail = 0, 0
    t0 = time.time()
    for name in targets:
        info = PARTS[name]
        stl_path = outdir / f"{name}.stl"
        print(f"-> {name:<28} ", end="", flush=True)
        success, err = render_part(info["call"], stl_path, openscad, fn)
        if success and stl_path.exists():
            print(f"OK   {fmt_size(stl_path.stat().st_size):>10}   ({info['desc']})")
            ok += 1
        else:
            print(f"FAIL {err[:80]}")
            fail += 1

    dt = time.time() - t0
    print(f"\nDone: {ok} OK, {fail} failed, total time {dt:.1f}s.")
    return 0 if fail == 0 else 5


if __name__ == "__main__":
    sys.exit(main())
